### ISSUE TITLE
The automatically created `scrape` is missing the `ScrapeSelector` label defined in `vmagent`.

### ISSUE THREAD

**Issue by qiuhefeng** [VictoriaMetrics/helm-charts#1213]
When I define `serviceScrapeSelector` in my `vmagent`, the `vmservicescrape` label automatically generated by `vmcluster` lacks a label. I hope the CR created by Helm charts can include the labels related to `serviceScrapeSelector`.

**Comment by AndrewChubatiuk** [comment]
hey @qiuhefeng
I'm not sure it's a common scenario, while not everyone expects that agent from chart with custom selector should scrape cluster metrics. E.g. operator allows to create multiple agents so another agent can be additionally configured for this purpose instead of built-in one. Also it's not obvious for a user, who reads chart configuration, that agent params will somehow impact cluster ones.
