### ISSUE TITLE
Kube state metric collection and K8s Grafana dashboards does not work when victoria-metrics-k8s-stack helm chart is used

### ISSUE THREAD

**Issue by hrbapna** [VictoriaMetrics/helm-charts#382]
I am trying to run VMSingle, Grafana, AlertManager using the VM kube stack to deploy in K8s.
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack
The setup is using the default values.yaml file. All apps defined in the helm chart are up in K8s but no K8s metric collection is done by the VM. Hence default grafana dashboards do not work.

Expectation: VM will monitor the K8s stack and all the grafana dashboards will work AS IS.
Observation: No targets are configured in VM and hence none of the grafana dashboards work.
Does this version of helm chart not work?
```
apiVersion: v2
name: victoria-metrics-k8s-stack
description: Kubernetes monitoring on VictoriaMetrics stack. Includes VictoriaMetrics Operator, Grafana dashboards, ServiceScrapes and VMRules
type: application
version: 0.12.4
appVersion: "1.81.2"
```

```
kubectl get VMServiceScrape -n monitoring
NAME                         AGE
vm-apiserver                 5h39m
vm-coredns                   5h39m
vm-grafana                   5h39m
vm-kube-controller-manager   5h39m
vm-kube-etcd                 5h39m
vm-kube-scheduler            5h39m
vm-kube-state-metrics        5h39m
vm-node-exporter             5h39m
vm-operator                  5h39m
vmagent-vm                   5h38m
vmalert-vm                   5h38m
vmalertmanager-vm            5h38m
vmsingle-vm                  5h38m
```

**Comment by ryan4yin** [comment]
I have a similar problem, and found the reason is that victoria-metrics-operator created Deployment `vmagent-victoria-metrics-k8s-stack` with `replicas: 0`, I adjust it to `1` and then everything works.

I then try to uninstall the helm release and reinstall, the issue just disappeared.

It may be some environment issue, the operator is not robust enough.

**Comment by b-a-t** [comment]
What do you mean by `no targets are configured`?

What I've observed in my case was the lack of default datasource in Grafana, hence it wasn't able to show any useful info.

Adding it manually fixed the issue. In my case **it seems** the problem was in the new logic introduced in the grafana helm chart and adding `initDatasources: true` option made things work again:
```yaml
  grafana:
    enabled: true
    sidecar:
      datasources:
        enabled: true
        initDatasources: true
```

**Comment by Haleygo** [comment]
Didn't look like a problem but some config missing.
Close it now, feel free to reopen if it's still a problem)
