### ISSUE TITLE
[QUERY] Switching from VMSingle configuration to VMCluster

### ISSUE THREAD

**Issue by navinpai** [VictoriaMetrics/helm-charts#501]
Just wanted to understand something that I couldn't find any docs around:

If I initially set up VictoriaMetrics using the helm chart in the `VMSingle` configuration and then have metrics data stored in it, will there be issues if we want to move from a `VMSingle` configuration to a `VMCluster` config _(or is this even possible)_? I'm asking because the simplicity of having a single `VMSingle` node/pod is very attactive _(always a fan of keeping things simple)_ but does that make it harder to move to a clustered setup once `VMSingle` starts hitting it's limits?

Thanks in advance! 😄

**Comment by totogtr** [comment]
Hi [zekker6](https://github.com/zekker6), following on this issue. Is `VMCluster` the recommended way to achieve HA or would a setup based on `VMSingle` could work ? If so what architecture would you recommend ?
Thanks !

**Comment by zekker6** [comment]
Hi @totogtr, it is possoble to build HA setup based on vmsingle. Please, see the attached schema.
![vm-single-ha](https://github.com/VictoriaMetrics/helm-charts/assets/1367798/5aaba9b5-b85a-4790-829a-ddd86c5b0e62)

In order to achieve HA with vmsingle you will need to deploy several vmsingle instances in different failure domains. Data should be written to all vmsingle instances. 
When reading data it is possible to load balance read requests between instances since data will be the same. Alternatively, it is possible to use passive-active model and forward read requests to active instance, in case of failure of active instance traffic can be directed to standby node.

Limitations of this setup are based on amount of resources which is possible to allocate to a single instance.
Clustered version on the other side scales easier because scaling of each component will improve performance. Also, load is distributed between different nodes which means tolerating outage of a single node is handled easier.

**Comment by totogtr** [comment]
Thanks for your detailed answer @zekker6 , it's exactly what I was looking for. 

In the setup you propose, could the VMAgent be 2 replicas of a single instance in 2 diffrent failure domains as detailted in the [ operator HA doc](https://docs.victoriametrics.com/operator/high-availability.html#vmagent) with multiple `remoteWrite` urls ?

**Comment by zekker6** [comment]
@totogtr Sure, here is scheme of such deployment.
![vm-single-ha(1)](https://github.com/VictoriaMetrics/helm-charts/assets/1367798/2103badc-7207-4c41-bb19-44eaac390a3c)


Please, note that when multiple vmagents are running their configuration must be identical and VMSingle must have [deduplication](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication) enabled. You will need to add `-dedup.minScrapeInterval` flag to both VMSigle instances with value equal to min value of scrape interval.

**Comment by totogtr** [comment]
Thank you for the detailed answer !
