### ISSUE TITLE
[Dashboards] CoreDNS dashboard has a wrong job name

### ISSUE THREAD

**Issue by sydorovdmytro** [VictoriaMetrics/helm-charts#732]
Hello people,

CoreDNS dashboard is broken. The reason is the job name in queries, it's `coredns`: 

`"expr": "up{job=\"coredns\", instance=~\"$instance\"}"` https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-system-coredns.yaml#L179 (just one example)

but it should be `{{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" $) "coredns" | trunc 63 | trimSuffix "-" }}`: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/servicemonitors/coredns.yaml#L30C9-L30C117

So the job name should not be hardcoded to a static value, or the ServiceMonitor needs a static name.

Another minor suggestion is to add a filter by the `cluster` label or at least add ad-hoc filters as we have for VM dashboards: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml#L5611

Thanks

**Comment by P-n-I** [comment]
Looks like other scrapes (node, e.g. kubelet) use `relabelConfigs` to ensure the `job` label is concise and consistent so the dashboards can rely on it.

**Comment by Haleygo** [comment]
@sydorovdmytro Since we don't maintain grafana dashboards ourselves, instead we use [this script](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py#L28) to sync them from multiple sources like https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master/dashboards.
So you can use what @P-n-I proposed here or modify the dashboard after install.

>Another minor suggestion is to add a filter by the cluster label or at least add ad-hoc filters as we have for VM dashboards

It's a good proposal, I think we should propose this to the upstream sources.
