### ISSUE TITLE
[victoria-metrics-k8s-stack] How to set type of vmselect service to NodePort?

### ISSUE THREAD

**Issue by Saigut** [VictoriaMetrics/helm-charts#756]
Hello, I want to expose vmui of victoria-metrics cluster. But I can't change vmselect service to NodePort, and I can't find how to set in values.yaml. (In the meanwhile, my-victoria-metrics-k8s-stack-grafana service can be set to NodePort in values.yaml)

Also it's no effects to edit vmselect-my-victoria-metrics-k8s-stack service directly.

How can I change the type of vmselect-my-victoria-metrics-k8s-stack to NodePort?

```
my-victoria-metrics-k8s-stack-grafana                     NodePort    10.233.32.217   <none>        80:30151/TCP                    2d20h
vmselect-my-victoria-metrics-k8s-stack                    ClusterIP   None            <none>        8481/TCP                        22h
```

**Comment by Haleygo** [comment]
Hello!
>Also it's no effects to edit vmselect-my-victoria-metrics-k8s-stack service directly.

Yes, you can't do that, since vm-operator is using vmcluster to manage vmselect resources, so your modification will be reverted.

>How can I change the type of vmselect-my-victoria-metrics-k8s-stack to NodePort?

The type of `vmselect-my-victoria-metrics-k8s-stack` is not allowed to change and it's headless by default because we use it to build `-selectNode` arg in vmselect, which is used to propagate cache reset request between vmselect nodes after [deletes time series](https://docs.victoriametrics.com/url-examples.html?highlight=tsdb/delete_series#apiv1admintsdbdelete_series).
But you can change the type under `vmselect.serviceSpec.spec`, in [values](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L197) of victoria-metrics-k8s-stack chart, it will be like
```
    vmselect:
      image:
        tag: v1.94.0-cluster
      ...
      serviceSpec:
        spec:
          type: NodePort
```
In this way, operator will create an additional service with type of `NodePort`.

**Comment by Saigut** [comment]
> serviceSpec:
>         spec:
>           type: NodePort

It works, and I succeed to expose vmui, thank you!
