### ISSUE TITLE
VMUI autocomplete problem

### ISSUE THREAD

**Issue by ydbdyds** [VictoriaMetrics/helm-charts#773]
I'm using the latest version of vmcluster (0.11.6), and found that auto-completion when editing prometheus expressions in vmui only works for metrics with initials a-e, is there some configuration introduced in the new version?

(I'm not experiencing this problem with version 0.9.32)

**Comment by Loori-R** [comment]
Hello, @ydbdyds 

vmui has added support for advanced auto-complete for label values and label names starting from version `1.95.0` (vmcluster `0.11.5`). However, there are some issues associated with these changes (refer to: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5348 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5342). It's possible that your problem is related to this.

To confirm, you should check the network tab. It's likely that vmui is not receiving all the metrics, which may not be immediately apparent. This could be due to parameters such as `limit`, `start`, and `end`.

**Comment by Haleygo** [comment]
Hi @ydbdyds ,
I'm closing this as it's not about helm-chart, please take a look at the issues that @Loori-R mentioned above, and feel free to create a new one in https://github.com/VictoriaMetrics/VictoriaMetrics/issues if they are not related to your problem)
