### ISSUE TITLE
Feature request: change scrape config to use endpointslice

### ISSUE THREAD

**Issue by tanisdlj** [VictoriaMetrics/helm-charts#862]
After upgrading to the latest operator for Kubernetes (v0.19.0 [victoria-metrics-k8s-stack-0.19.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.19.0) ), we started getting a lot of warnings logged in vmagent that are

```
12T15:07:49.554Z    warn    VictoriaMetrics/lib/promscrape/discovery/kubernetes/endpoints.go:112    the number of targets for "role: endpoints" "default/my-service" exceeds 1000 and has been truncated; please use "role: endpointslice" instead
```

and AlertManager started to alert about "TooManyScrapeErrors".

If the solution is to use endpointslice, we should change this scrapes by default in the config

**Comment by Haleygo** [comment]
Hello @tanisdlj ,
It shouldn't related to operator version or vmagent version change, since we [added this warn message](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/3408a05d124c05b63853ec0fe2a80fbed6c51053) two years ago. 
I don't think we need change role types to `endpointslice` by default, since for most workloads, backend endpoints number is less than 1000 and won't be truncated by Kubernetes. 

Which scrape job you refer here with the scrape error, a builtin job in victoria-metrics-k8s-stack chart or a customized one?
If you see this warn message and all the discovered targets are needed, you need to fix the job by changing type.
